name: matrec

dependencies:
  - h5py
  - hdf5
  - pandas
  - python=3.8
  - yaml
  - matplotlib
  - seaborn
  - pip
  - scipy
  - scikit-learn
  - tqdm
  - numpy==1.20.3

  - pip:
    - torch==1.7.0
    - pymatgen==2022.11.7
    - robocrys==0.2.7
    - matminer==0.6.2
